### ISSUE TITLE
API

### ISSUE THREAD

**Issue by GalackQSM** [zyrouge/xeno-bot-list#9]
Is there an API to count the number of servers etc?

**Comment by scientific-dev** [comment]
What do u mean?

**Comment by GalackQSM** [comment]
have an API like top.gg to display the number of servers because on the source the number of servers remains at zero

**Comment by scientific-dev** [comment]
You shall ask zyrouge for it

**Comment by ghost** [comment]
There is no api.

**Comment by GalackQSM** [comment]
He must necessarily have an API because the number of servers is zero so if he put that it's not for nothing

**Comment by ghost** [comment]
There is no api, I have checked the whole code :/

**Comment by ghost** [comment]
https://discord.gg/Rf3xPMm

**Comment by scientific-dev** [comment]
Btw what happened to the botlist. I went to the site and it is saying `The site can't be reached`

Its [https://botlist.zyrouge.gq/](https://botlist.zyrouge.gq/) right?

**Comment by twlite** [comment]
API: https://dev.zyrouge.gq/botlist/api/docs

**Comment by ghost** [comment]
Hmm I tried using that api, but it didn't worked, I knew there was no code with it...
@Snowflake107

**Comment by ghost** [comment]
Idk how u got that api doc

**Comment by zyrouge** [comment]
https://botlist.zyrouge.gq/ (Old & won't be updated) doesn't work anymore, use https://dev.zyrouge.gq/botlist (New & closed-source)

**Comment by GalackQSM** [comment]
@zyrouge you source API ?
